### ISSUE TITLE
Dispose can cause application to hang

### ISSUE THREAD

**Issue by jsearles** [serilog/serilog-sinks-periodicbatching#21] opened 2018-06-19 15:21 UTC
I've been testing failure scenarios with a sink that relies on this base class. What i've found is that if the queue is failing to log during disposal, the application will hang for an extended period while the sink continually backs off and retries sending the messages. The retry and backoff settings are not exposed, so there is no way to control this. In normal use cases the backoff/retry settings in place are fine, however during disposal we would want to fail more quickly to prevent the application from hanging. Perhaps exposing a timeout duration during disposal would be a simple approach that could resolve the issue at hand. What do you think?

**Comment by nblumhardt** [comment] 2018-06-20 06:08
Hi, thanks for the note!

The `Dispose()` method calls `CloseAndFlush()` directly, which itself directly calls `OnTick()`; it's only the timer reset at the end of `OnTick()` that's impacted by exponential backoff/retry as far as I recall. Could the pause be elsewhere?

Any help tracking this down to a precise call graph/path would be appreciated, the sink is definitely designed with the intention of avoiding this kind of behavior :+1: 

Thanks!
Nick

**Comment by jrsearles** [comment] 2018-06-25 13:52
Thanks for the reply - i'll see if i can get a reproduction to narrow it down.

**Comment by jsearles** [comment] 2018-06-26 18:11
OK - i've been unable to replicate this in isolation and looking at the how disposal is handled here i believe the problem is more likely in our code. Thanks for your time.

**Comment by jsearles** [comment] 2018-06-27 13:15
I've figured out the cause of the hanging - if there are queued messages being processed during shutdown and those messages are failing, it will continue the retry logic, causing the application to hang until retries are exhausted.

**Comment by skomis-mm** [comment] 2018-06-27 14:32
@jsearles can you provide some repro example? I could not reproduce this. Disposing sink  [turns off](https://github.com/serilog/serilog-sinks-periodicbatching/blob/dev/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs#L197) the retry logic so when exception is thrown the queue will stop processing. 
Is there some custom retry logic inside overriden `EmitBatchAsync(..)`?

**Comment by jsearles** [comment] 2018-06-28 19:59
OK - i'm able to reproduce it reliably in a sample app. Looks like a deadlock that is occurring [here](https://github.com/serilog/serilog-sinks-periodicbatching/blob/dev/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PortableTimer.cs#L128). I'll put together a repo i can share.

**Comment by nblumhardt** [comment] 2018-06-29 21:16
@jsearles great! Sounds like we're closing in on it.

Is this a publicly-available sink, or a custom/internal one?

**Comment by gregpakes** [comment] 2018-12-20 14:31
Is there any news on this?  I am getting periodic thread exhaustion in my application and it points to the same issue...  I have 514 threads all blocked with the following stacktrace:

![image](https://user-images.githubusercontent.com/102243/50290567-fd552580-0463-11e9-9f93-7838af944bd1.png)

**Comment by skomis-mm** [comment] 2018-12-20 15:04
Hi, @gregpakes . Can you give more help on this?
1. What sink do you use?
2. If sink is custom one, how its implementation looks like (overriden EmitBatchAsync method)?
3. How does logging setup look like?
4. Is it possible to get minimal repro example? 

Thanks!

**Comment by gregpakes** [comment] 2018-12-20 15:12
Hi,

1. This is being used by the Seq sink.
2. It is not custom (https://github.com/serilog/serilog-sinks-seq)
3. Logging setup looks like this in our IOC container:

```
 init.For<ILogger>()
                            .Use(
                                ctx =>
                                    {
                                        var seqServer =
                                            WebConfigurationManager.AppSettings["serilog:write-to:Seq.serverUrl"];
                                        var seqApiKey =
                                            WebConfigurationManager.AppSettings["serilog:write-to:Seq.apiKey"];
                                        var appService = ctx.GetInstance<IApplicationService>();

                                        var logger = new LoggerConfiguration()
                                            .WriteTo.Seq(seqServer, apiKey: seqApiKey)
                                            .Enrich.WithProperty("Version", appService.GetVersion())
                                            .Enrich.WithProperty("Client", appService.GetClientName())
                                            .CreateLogger();

                                        return logger;
                                    });
```
4.  I think this will be tricky.  We are running this on hundreds of sites and it crops up very rarely.

**Comment by skomis-mm** [comment] 2018-12-20 15:26
@gregpakes , thanks for the info, it seems that you use StructureMap. Can you check that this registration is actually singleton? As a rule, Logger should be created once. 
If registration is transient then each resolve operation will create new instance of the logger with its sinks (and timers) that won't be correctly disposed.

**Comment by gregpakes** [comment] 2018-12-20 15:32
Thanks - I will take a look.  It doesn't look like a singleton at the moment.

**Comment by nblumhardt** [comment] 2019-03-13 00:56
Closing this, assuming that the problem was container configuration; but let us know if not, folks :-) Cheers!

**Closed as completed by nblumhardt** 2019-03-13 00:56 UTC

**Comment by kosmakoff** [comment] 2019-12-17 13:39
Hi. I'd like to report that this is still an issue, at least for my configuration.

I am using the [AWS CloudWatch Sink](https://github.com/Cimpress-MCP/serilog-sinks-awscloudwatch) based on this project, and sometimes during automatic tests the same deadlocking behavior occurs.

The serilog logger is registered with .NET Core DI container as scoped. It is important that it is scoped, as it is being used in AWS Lambdas, where the container is reused across requests, and the new ILogger instance is resolved per request, so that I have control over it's disposal - I need to be sure that all buffered log messages get written to AWS.

**Comment by skomis-mm** [comment] 2019-12-17 17:16
Hi, @kosmakoff . I would not recommend to scope `ILogger` instances. If you only need to ensure that every message should get written to AWS you can flush events at the end of the application lifetime or test run in your case via `Log.CloseAndFlush` or `ILogger.Dispose`. 

There are several problems scoping `ILogger` instances per request:
1. the I/O sinks which utilize PBS are designed to be singleton per endpoint. If you look at the implementation of the AWS CloudWatch sink you will see it has custom buffering, limitation and retry logic. When scoping `ILogger`s per request it will result in parallel logging pipelines with its own state and logic around it.
2. when you dispose the logger the actual disposal is synchronous. But since sinks's flushing is I/O call it will result in slow calls. And when its slow, and it is for every request, and every request is handled by thread pool thread its very easy to have thread starvation that leads to hangs/timeouts (not deadlocks). And this side effect is global and affect entire application which is very bad. 

If its really deadlocks, it would be great if you could provide more info such as stack traces of the hanged threads, configuration etc or minimal project that can help to reproduce this. Thanks!

**Comment by nblumhardt** [comment] 2019-12-17 21:30
> or `ILogger.Dispose`

Just a tiny clarification, @skomis-mm means `Logger.Dispose`, here.
