### ISSUE TITLE
PeriodicBatchingSink writes first message immediately on .NET Core.

### ISSUE THREAD

**Issue by pakrym** [serilog/serilog-sinks-periodicbatching#7] opened 2016-08-29 19:36 UTC
When using `PeriodicBatchingSink` on .NET Core first call to `Emit` causes immediate call to `EmitBatchAsync` with a single event passed in.

Works as expected on full framework.

**Comment by nblumhardt** [comment] 2016-08-29 23:21
Thanks for the note, Pavel.

This one's by design, since in many "F5" scenarios we otherwise would receive reports that logging wasn't working. Users would run their (console) app in development, flick over and refresh the log in a second or so, and not see any data. By sending the first event immediately we manage to avoid this and don't get as many false bug reports now.

Is the behaviour causing problems in your scenario?

Cheers!

**Comment by pakrym** [comment] 2016-09-01 16:06
Issue is not in behavior itself but in fact that it is different for full framework and coreclr. On full framework I see a single batch after a period.

It makes it very hard to unit test `PeriodicBatchingSink` based sink.

**Comment by nblumhardt** [comment] 2016-09-04 22:23
Thanks for the follow up. This'll be because of the implementation differences of the timers on the two platforms.

Ideally we'll either:
1. Use our custom `PortableTimer` on all platforms, or
2. Get `Timer.Dispose(WaitHandle)` in .NET Core (https://github.com/dotnet/corefx/issues/2942), or
3. Adopt @dsplaisted's workaround from https://github.com/Microsoft/dotnet-apiport/pull/283 and go back to `Timer` on all platforms.

I'd prefer (2), since it's the best-tested code path we have right now, but unless it's "coming soon" we should probably reconsider (1) and (3) to get some consistency across the two runtimes. Not sure which is the safer option at this point in time.

**Comment by skomis-mm** [comment] 2016-09-05 08:24
@nblumhardt , I think the problem described above related to the fact that `PortableTimer` dispatches tick event when `interval == TimeSpan.Zero` (first log event) synchronously (and probably unwanted with with the fact that sink's `EmitBatch()` is also synchronous and blocking). In contrast, `System.Threading.Timer` with `TimeSpan.Zero` invokes tick handler on a `ThreadPool` thread. 
So to make behavior consistent I believe current `PortableTimer` can be fixed with `Task.Run(..)` for the first event or `Task.Delay(interval).ContinueWith()` with `TaskScheduler.Default` specified with some sync around `_state`.

For options you described I'd vote for (3) (until (2) implemented) since  `System.Threading.Timer` is available on `netstandard12+` and overall implementation will use single underlying timer instead of many with `Task.Delay()`.

**Comment by nblumhardt** [comment] 2016-09-06 00:43
@skomis-mm thanks for the analysis, I think that makes sense.

**Closed as completed** 2016-09-12 06:52 UTC

**Comment by splendid25** [comment] 2016-10-05 08:54
Hello,

It seems the timer consistency has been fixed, but I have a problem regarding the first log.

I understand the default behavior, to send the first event, but it can't find how to override it.
I am implementing a BatchEmailSink, to group logs into mails, so I have a first mail with one line only, and all the rest follows after the timer ticks or the queue is full. I would rather have all the events in a single mail.

Is it possible to implement a Boolean to queue the first event, which would be false by default to avoid breaking change ?

Thanks
