### ISSUE TITLE
First event is fired right away - it is not desired for email sink. Shall we add a flag for this option?

### ISSUE THREAD

**Issue by avs099** [serilog/serilog-sinks-periodicbatching#36] opened 2019-11-12 15:49 UTC
please see this line: https://github.com/serilog/serilog-sinks-periodicbatching/blob/c4d521bad90cb96adf2a4900c03a9aab519631de/src/Serilog.Sinks.PeriodicBatching/Sinks/PeriodicBatching/PeriodicBatchingSink.cs#L244

because of it, first event will be sent to all sinks right away. In particular case of https://github.com/serilog/serilog-sinks-email that would mean an email will be deployed with single event - and then another email would come later with more information. That's quite confusing and undesired. I suggest we add a flag to allow more refined control for this. Would you accept such change request? Please let me know and I will work on it.

**Comment by nblumhardt** [comment] 2019-11-12 23:46
Thanks for the note!

This is a duplicate of https://github.com/serilog/serilog-sinks-email/issues/47 - it's closed, but we'd be open to a PR in _Serilog.Sinks.Email_ that broke the `PeriodicBatchingSink` dependency and made this improvement. Thanks!

**Closed as completed by nblumhardt** 2019-11-12 23:46 UTC

**Comment by avs099** [comment] 2019-11-13 01:05
> but we'd be open to a PR in _Serilog.Sinks.Email_ that broke the `PeriodicBatchingSink` dependency and made this improvement.

Couple of clarifications please (to make sure PR would be acceptable). Do you want to keep the same "batching" logic (more or less)? Eg X messages or T minutes before sending email? if that's the case I'm afraid the PR will be very much similar to the existing code of `PeriodicBatchingSink` class. Are you okay with that? I can simply it a bit - eg remove `BoundedConcurrentQueue` - but high level it will remain a copy/paste.

**Comment by nblumhardt** [comment] 2019-11-13 01:09
The closer to the current PeriodicBatchingSink, the better, I think - less review time required, and we can re-use tests :-) 👍 

Maintenance on _Serilog.Sinks.Email_ has fallen behind a bit, I can help review this but you may need to `@` mention me in the PR. Cheers!
